### ISSUE TITLE
npm为什么安装不了呀？

### ISSUE THREAD

**Issue by wodog** [nswbmw/cli-chat#1]
``` bash
zhouchongyangdeMac-mini:node_modules zhouchongyang$ sudo npm install -g cli-chat
/usr/local/bin/cli-chat -> /usr/local/lib/node_modules/cli-chat/bin/cli-chat

> weak@1.0.0 install /usr/local/lib/node_modules/cli-chat/node_modules/weak
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/zhouchongyang/.node-gyp/5.1.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/cli-chat/node_modules/weak/.node-gyp"
```

安装到了这里就卡住了，然后^C后执行命令, 报以下错误

``` bash
^CzhouchongyangdeMac-mini:node_modules zhouchongyang$ cli-chat
/usr/local/lib/node_modules/cli-chat/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/cli-chat/node_modules/weak/build/weakref.node
 → /usr/local/lib/node_modules/cli-chat/node_modules/weak/build/Debug/weakref.node
 → /usr/local/lib/node_modules/cli-chat/node_modules/weak/build/Release/weakref.node
 → /usr/local/lib/node_modules/cli-chat/node_modules/weak/out/Debug/weakref.node
 → /usr/local/lib/node_modules/cli-chat/node_modules/weak/Debug/weakref.node
 → /usr/local/lib/node_modules/cli-chat/node_modules/weak/out/Release/weakref.node
 → /usr/local/lib/node_modules/cli-chat/node_modules/weak/Release/weakref.node
 → /usr/local/lib/node_modules/cli-chat/node_modules/weak/build/default/weakref.node
 → /usr/local/lib/node_modules/cli-chat/node_modules/weak/compiled/5.1.1/darwin/x64/weakref.node
    at bindings (/usr/local/lib/node_modules/cli-chat/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/cli-chat/node_modules/weak/lib/weak.js:7:35)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at new D (/usr/local/lib/node_modules/cli-chat/node_modules/dnode/index.js:28:20)
    at module.exports (/usr/local/lib/node_modules/cli-chat/node_modules/dnode/index.js:8:12)
zhouchongyangdeMac-mini:node_modules zhouchongyang$ 
```

**Comment by nswbmw** [comment]
node 版本？

**Comment by nswbmw** [comment]
现在去掉 dnode，用原生 dgram(udp) 了。
